#! /bin/sh

# everything to get bspwm working
sxhkd &
~/.fehbg
~/.config/polybar/launch.sh
compton &

bspc monitor -d 0001 0010 0011 0100 0101 0110 0111 1000 1001 1010

bspc config border_width         0
bspc config window_gap           8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
